name: Aplicação Django

on: [ pull_request ]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - name: instalar dependencias
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: rodar testes automaticos
        run: |
          pipenv run pytest webdev
          
